### PR TITLE
Release notes

### PR DESCRIPTION
**Pull request by dehanj**
- Correct links to example applications using tkeysign in readme
- release notes

### CODE REVIEW

**Comment by mchack-work** [comment]
- Let's use v1.0.0 for the next release.
- Update Go dependencies, which also means using a tagged version of tkeyclient!

Strangely, go.bug.st/serial updated to v1.6.2 but tkeyclient has 1.6.1. Not what I expected.

Tested on Linux with tkey-ssh-agent and works fine. Needs testing on macOS and Windows.

**Comment by dehanj** [comment]
Not what I expected either, and it seems that it does not have any direct dependency to it either:

```
$ go mod why go.bug.st/serial 
# go.bug.st/serial
github.com/tillitis/tkeysign
github.com/tillitis/tkeyclient
go.bug.st/serial
```

It works on macos.
Another option is to pin it to v.1.6.1.

**Comment by dehanj** [comment]
Put the history in a better order, added upadeted go packages to release notes and squashed.

**Comment by dehanj** [comment]
Tested and working on Windows.

**Comment by mchack-work** [comment]
tkeyclient has been updated. Let's tag tkeyclient and then update tkeyclient dep here, then merge.

**Comment by dehanj** [comment]
Read up about what `go get -u` does, and apparently it is expected. 
It updates the specified packages and their dependencies to the **latest minor or patch version** according to semantic versioning.

So latest minor och patch version are assumed (which it should according to semantic versioning) compatible and should be safe to use. 

I have bumped to tkeyclient v1.0.0, squashed and ready.

**Review by mchack-work — APPROVED** [review]
Ran go mod tidy to clean go.sum. Squashed. Looks good.

**Pull request merged**
